name: Learn_workflow
on: 
  push:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        run: echo " runnig success............................."
      - name: clone
        uses: actions/checkout@v6.0.2
      - name: build docker image
        run: docker build -t sree471/learn2:v_${{github.run_number}} .
      - name: show docker images
        run: docker images
        
